// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MonikerOnToolWindow.ToolWindow
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMonikerOnToolWindowPackageString = "ba8e4e21-b35f-41bb-97e1-14f9cdf950c7";
        public static Guid guidMonikerOnToolWindowPackage = new Guid(guidMonikerOnToolWindowPackageString);

        public const string guidMonikerOnToolWindowPackageCmdSetString = "e66135b6-c7e3-4e26-9def-4ea4c41e53cd";
        public static Guid guidMonikerOnToolWindowPackageCmdSet = new Guid(guidMonikerOnToolWindowPackageCmdSetString);

        public const string guidImagesString = "306936d5-0827-401b-b0e8-6ae2f9350237";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SimpleToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}