// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TopLevelMenu
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTopLevelMenuPackageString = "9418e7b8-2cd6-4eb6-bc08-51079ce63fb7";
        public static Guid guidTopLevelMenuPackage = new Guid(guidTopLevelMenuPackageString);

        public const string guidTopLevelMenuPackageCmdSetString = "e454edbd-a9f8-4a80-9def-a136cc18fe9a";
        public static Guid guidTopLevelMenuPackageCmdSet = new Guid(guidTopLevelMenuPackageCmdSetString);

        public const string guidImagesString = "044621b6-be43-4326-9dc9-a365e63c3923";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}