// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CheckableMenuCommand.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCheckableMenuCommandPackageString = "0945e5bb-91e2-4416-98e3-adfae01aa2d1";
        public static Guid guidCheckableMenuCommandPackage = new Guid(guidCheckableMenuCommandPackageString);

        public const string guidCheckableMenuCommandPackageCmdSetString = "5337bf40-159b-418a-b570-63d9982ee724";
        public static Guid guidCheckableMenuCommandPackageCmdSet = new Guid(guidCheckableMenuCommandPackageCmdSetString);

        public const string guidImagesString = "b5e3315e-d246-48a9-b5d6-949306e57f35";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CheckableCommandId = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}