// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReadVsStoreConfigSettings.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidReadVsStoreConfigSettingsPackageString = "6a560577-c8e0-4192-afb2-a3aa0753164e";
        public static Guid guidReadVsStoreConfigSettingsPackage = new Guid(guidReadVsStoreConfigSettingsPackageString);

        public const string guidReadVsStoreConfigSettingsPackageCmdSetString = "49a80375-de9b-41b9-acdf-21aff807f043";
        public static Guid guidReadVsStoreConfigSettingsPackageCmdSet = new Guid(guidReadVsStoreConfigSettingsPackageCmdSetString);

        public const string guidImagesString = "dd4e968f-1de7-4104-82ba-abc05469c21c";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CheckWindowsPhoneDevToolsCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}