// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AssignKeyboardShortcut.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAssignKeyboardShortcutPackageString = "c984b38b-d482-4af0-b8ee-4fb2cd0381c5";
        public static Guid guidAssignKeyboardShortcutPackage = new Guid(guidAssignKeyboardShortcutPackageString);

        public const string guidAssignKeyboardShortcutPackageCmdSetString = "a709ae07-1789-4e55-a0c9-8bdd2721eddd";
        public static Guid guidAssignKeyboardShortcutPackageCmdSet = new Guid(guidAssignKeyboardShortcutPackageCmdSetString);

        public const string guidImagesString = "c8b69827-0fb7-453a-9a18-cbf6d3176be4";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}