// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FirstTimeAfterExtensionIsInstalled.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFirstTimeAfterExtensionIsInstalledPackageString = "6505ef2e-d410-4e1b-8648-4daebd364e6d";
        public static Guid guidFirstTimeAfterExtensionIsInstalledPackage = new Guid(guidFirstTimeAfterExtensionIsInstalledPackageString);

        public const string guidFirstTimeAfterExtensionIsInstalledPackageCmdSetString = "ace77e9b-58ec-47b8-b333-2821338a6a25";
        public static Guid guidFirstTimeAfterExtensionIsInstalledPackageCmdSet = new Guid(guidFirstTimeAfterExtensionIsInstalledPackageCmdSetString);

        public const string guidImagesString = "d27796af-5f34-4542-ac87-6ad2a65c38cb";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string autoloadString = "6c650c5a-d7d6-407b-993f-426d53ddbdde";
        public static Guid autoload = new Guid(autoloadString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SomeCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}