// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfTextViewIntro.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWpfTextViewIntroPackageString = "a9b19c19-0e6c-466e-8ce7-a8c9f3f5809b";
        public static Guid guidWpfTextViewIntroPackage = new Guid(guidWpfTextViewIntroPackageString);

        public const string guidWpfTextViewIntroPackageCmdSetString = "1bbde6b5-3d9a-44f5-bf05-ad3e8d4cd021";
        public static Guid guidWpfTextViewIntroPackageCmdSet = new Guid(guidWpfTextViewIntroPackageCmdSetString);

        public const string guidImagesString = "45286256-3e2f-4267-a8bf-88a85ada74eb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int WpfCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}