// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RemoveAllComments.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidRemoveAllCommentsPackageString = "14fa454f-a271-44af-a656-b7f3b93571f4";
        public static Guid guidRemoveAllCommentsPackage = new Guid(guidRemoveAllCommentsPackageString);

        public const string guidRemoveAllCommentsPackageCmdSetString = "52dc7de1-f658-46de-b1b8-a52489ce61ed";
        public static Guid guidRemoveAllCommentsPackageCmdSet = new Guid(guidRemoveAllCommentsPackageCmdSetString);

        public const string guidImagesString = "c8c42870-04ed-4869-a33e-9882570051e1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int RemoveAllCommentsCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}