// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace AutofacComnityToolKitNotWorking
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AutofacComnityToolKitNotWorkingString = "31669251-53ca-45ab-a6d8-480dec715da1";
        public static Guid AutofacComnityToolKitNotWorking = new Guid(AutofacComnityToolKitNotWorkingString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}