// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IWpfTextViewHostIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidIWpfTextViewHostIntroPackageString = "c08d2c2e-882a-4435-9c15-fe20c2482742";
        public static Guid guidIWpfTextViewHostIntroPackage = new Guid(guidIWpfTextViewHostIntroPackageString);

        public const string guidIWpfTextViewHostIntroPackageCmdSetString = "540aa6b4-1981-4e6a-bb0b-8f18f7d95ced";
        public static Guid guidIWpfTextViewHostIntroPackageCmdSet = new Guid(guidIWpfTextViewHostIntroPackageCmdSetString);

        public const string guidImagesString = "efd62ced-e7b1-4efe-b96a-0f55360542c3";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}