// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IFileExtRegSer.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidIFileExtRegSerPackageString = "c83301cb-b8be-4920-8504-eea995638e6d";
        public static Guid guidIFileExtRegSerPackage = new Guid(guidIFileExtRegSerPackageString);

        public const string guidIFileExtRegSerPackageCmdSetString = "1b1daa23-070f-4fd4-adb2-3290dd632efe";
        public static Guid guidIFileExtRegSerPackageCmdSet = new Guid(guidIFileExtRegSerPackageCmdSetString);

        public const string guidImagesString = "4b3c9aae-4ab2-4a3f-8724-9d335c29a574";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}