// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixCommunityInsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixCommunityInsertGuid.6f6fb24f-ac1e-4d70-a085-34973632e0a0";
        public const string Name = "VsixCommunityInsertGuid";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
