// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ContentTypeRegistryServiceIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidContentTypeRegistryServiceIntroPackageString = "3f7806d4-b4d9-4416-8447-3933c4ea7ba8";
        public static Guid guidContentTypeRegistryServiceIntroPackage = new Guid(guidContentTypeRegistryServiceIntroPackageString);

        public const string guidContentTypeRegistryServiceIntroPackageCmdSetString = "032ec808-c390-4348-857f-8cc2491a8071";
        public static Guid guidContentTypeRegistryServiceIntroPackageCmdSet = new Guid(guidContentTypeRegistryServiceIntroPackageCmdSetString);

        public const string guidImagesString = "bc950005-ac25-45eb-8d36-86ee5c5e8de8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int DisplayContentTypesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}