// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ComponentModelIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidComponentModelIntroPackageString = "33ac943f-36ea-413e-add4-a826b9d5a7c5";
        public static Guid guidComponentModelIntroPackage = new Guid(guidComponentModelIntroPackageString);

        public const string guidComponentModelIntroPackageCmdSetString = "10316be7-4b9d-4dbc-9df7-a441f1c28954";
        public static Guid guidComponentModelIntroPackageCmdSet = new Guid(guidComponentModelIntroPackageCmdSetString);

        public const string guidImagesString = "8bd939aa-435f-42f8-b185-f532215dfbb7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}