// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ButtonWithVisibilityConstraints.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidButtonWithVisibilityConstraintsPackageString = "508ffd1a-37af-4445-be4b-b321feed260d";
        public static Guid guidButtonWithVisibilityConstraintsPackage = new Guid(guidButtonWithVisibilityConstraintsPackageString);

        public const string uiContextSupportedFilesString = "24551deb-f034-43e9-a279-0e541241687e"; // Must match guid in VsCommandTable.vsct
        public static Guid uiContextSupportedFiles = new Guid(uiContextSupportedFilesString);

        public const string guidButtonWithVisibilityConstraintsPackageCmdSetString = "7ca17223-d0f2-47a4-85d0-697e6636fd45";
        public static Guid guidButtonWithVisibilityConstraintsPackageCmdSet = new Guid(guidButtonWithVisibilityConstraintsPackageCmdSetString);

        public const string guidImagesString = "1891515b-4e0c-498d-88f0-fcccb1534af5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CsVbFileVisibleCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}