//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 17.0.0.4
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace ManifestToCode
{
    public static class MyImageIds
    {
        public const string AssetsGuidString = "{ece32f48-0480-4455-8354-56d38251e95e}";
        public static readonly Guid AssetsGuid = new Guid(AssetsGuidString);

        public const int Save = 0;
    }
}
