// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GetSelectionHighlight.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGetSelectionHighlightPackageString = "0a9bb03a-15c6-4ced-9349-029b188a4ba0";
        public static Guid guidGetSelectionHighlightPackage = new Guid(guidGetSelectionHighlightPackageString);

        public const string guidGetSelectionHighlightPackageCmdSetString = "4bd1cefd-c173-4c28-b509-4f83e0d36759";
        public static Guid guidGetSelectionHighlightPackageCmdSet = new Guid(guidGetSelectionHighlightPackageCmdSetString);

        public const string guidImagesString = "b6336158-bcaa-467c-83be-6c2f89110517";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GetSelectionHighlightCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}