// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MenuCommandTest
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidMenuCommandTestPackageString = "9bcf13c9-ac2a-4e34-af3c-df92bc595954";
        public static Guid guidMenuCommandTestPackage = new Guid(guidMenuCommandTestPackageString);

        public const string guidMenuCommandTestPackageCmdSetString = "8ced5348-3b98-408d-b45c-610bf0b5a474";
        public static Guid guidMenuCommandTestPackageCmdSet = new Guid(guidMenuCommandTestPackageCmdSetString);

        public const string guidImagesString = "816558c7-7498-4769-8e3d-f16b58314c14";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddAdornmentId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}