// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleToolWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "SimpleToolWindow.6414be47-856d-446e-98a0-24bc584eb269";
        public const string Name = "SimpleToolWindow";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
