// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuidContextMenu.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidInsertGuidContextMenuPackageString = "5eab927d-8b20-41d1-9702-e22b1f847494";
        public static Guid guidInsertGuidContextMenuPackage = new Guid(guidInsertGuidContextMenuPackageString);

        public const string guidInsertGuidContextMenuPackageCmdSetString = "7b257042-a7bd-4af2-9819-0b52d3d1f4bd";
        public static Guid guidInsertGuidContextMenuPackageCmdSet = new Guid(guidInsertGuidContextMenuPackageCmdSetString);

        public const string guidImagesString = "140de86a-1419-4f81-8809-4fede77f5ded";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int InsertGuidContextCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}