// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CaretPositionOnToolWindow
{
    internal sealed partial class Vsix
    {
        public const string Id = "CaretPositionOnToolWindow.74e21d09-ba99-4f98-93d7-cc46dc8a5aa7";
        public const string Name = "CaretPositionOnToolWindow";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
