// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TaggerInTextModel.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTaggerInTextModelPackageString = "6cdf45df-c9df-4d50-ba01-9a8dc5753c1d";
        public static Guid guidTaggerInTextModelPackage = new Guid(guidTaggerInTextModelPackageString);

        public const string guidTaggerInTextModelPackageCmdSetString = "a721e47c-6b19-4e59-bf12-a49ff3c32522";
        public static Guid guidTaggerInTextModelPackageCmdSet = new Guid(guidTaggerInTextModelPackageCmdSetString);

        public const string guidImagesString = "5f427df3-4145-4f94-9892-22b972e2e789";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ShowTagCountCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}