// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditorOptions
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageEditorOptions.292b7127-622d-41cc-ab8e-15612b6af83e";
        public const string Name = "LinqLanguageEditorOptions";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
