// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditorOptions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LinqLanguageEditorOptionsString = "e77924cc-f23c-463f-aece-54f6a685bf63";
        public static Guid LinqLanguageEditorOptions = new Guid(LinqLanguageEditorOptionsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LinqOptionsToolWindowCommandId = 0x0100;
    }
}