// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddMenuButtonVsMainMenuBar.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddMenuButtonVsMainMenuBarPackageString = "354d7ab4-a2b5-4c93-82c4-8169ca380017";
        public static Guid guidAddMenuButtonVsMainMenuBarPackage = new Guid(guidAddMenuButtonVsMainMenuBarPackageString);

        public const string guidAddMenuButtonVsMainMenuBarPackageCmdSetString = "15ec0eb6-41aa-4b61-8259-5e07eeb95f18";
        public static Guid guidAddMenuButtonVsMainMenuBarPackageCmdSet = new Guid(guidAddMenuButtonVsMainMenuBarPackageCmdSetString);

        public const string guidImagesString = "bf19cb4b-7eff-47a1-a8cf-348faddfbdb1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AddMenuButtonCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}