// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolWindowWithToolBar.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolWindowWithToolBarPackageString = "92b8ff5f-4b8b-480b-b288-afb0d2a407c4";
        public static Guid guidToolWindowWithToolBarPackage = new Guid(guidToolWindowWithToolBarPackageString);

        public const string guidToolWindowWithToolBarPackageCmdSetString = "8c6b1675-eff9-469b-8786-4e30d86bf487";
        public static Guid guidToolWindowWithToolBarPackageCmdSet = new Guid(guidToolWindowWithToolBarPackageCmdSetString);

        public const string guidImagesString = "1ecc7de7-c2cf-4075-abae-b922b2d1a351";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AsyncToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}