// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ToolWindowWithToolBar.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolWindowWithToolBarPackageString = "7aef415a-6359-46e2-9100-f32d60b99ec5";
        public static Guid guidToolWindowWithToolBarPackage = new Guid(guidToolWindowWithToolBarPackageString);

        public const string guidToolWindowWithToolBarPackageCmdSetString = "8ceb06ac-a603-4393-b5db-c6b551262a8c";
        public static Guid guidToolWindowWithToolBarPackageCmdSet = new Guid(guidToolWindowWithToolBarPackageCmdSetString);

        public const string guidImagesString = "105dc062-2db4-41b2-8ee8-f9aac33d1248";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "72e30b87-b7bf-4cfd-abee-341bd88fcbe1";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToolBarOnToolWindowCommandId = 0x0100;
        public const int cmdidAsyncToolWindowCommand = 0x1021;
        public const int TWToolbar = 0x1000;
        public const int TWToolbarGroup = 0x1050;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int bmpPic11 = 0x0001;
        public const int bmpPic12 = 0x0002;
        public const int bmpPicSearch1 = 0x0003;
        public const int bmpPicX1 = 0x0004;
        public const int bmpPicArrows1 = 0x0005;
        public const int bmpPicStrikethrough1 = 0x0006;
    }
}