// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WriteVsStoreConfigSettings.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWriteVsStoreConfigSettingsPackageString = "8485adc6-164b-4fbd-8312-954c17c9a2ef";
        public static Guid guidWriteVsStoreConfigSettingsPackage = new Guid(guidWriteVsStoreConfigSettingsPackageString);

        public const string guidWriteVsStoreConfigSettingsPackageCmdSetString = "34618b87-6910-4ba8-a396-f2b7a09797f0";
        public static Guid guidWriteVsStoreConfigSettingsPackageCmdSet = new Guid(guidWriteVsStoreConfigSettingsPackageCmdSetString);

        public const string guidImagesString = "6bdc47fb-154d-4b95-8dc4-749699298aec";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int WriteToUserSettingsCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}