// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileExtToContentTypeDefIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFileExtToContentTypeDefIntroPackageString = "a5e4c932-6981-42f6-ad6d-f6f708f0cc53";
        public static Guid guidFileExtToContentTypeDefIntroPackage = new Guid(guidFileExtToContentTypeDefIntroPackageString);

        public const string guidFileExtToContentTypeDefIntroPackageCmdSetString = "06b534bb-70a4-4f0c-89d0-89f0e81f06bb";
        public static Guid guidFileExtToContentTypeDefIntroPackageCmdSet = new Guid(guidFileExtToContentTypeDefIntroPackageCmdSetString);

        public const string guidImagesString = "40dddc2a-bbd6-4c76-a307-582bd99cb4d5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}