// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsctCompletion
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTestCommandHereWeGoPackageString = "163343e3-3aec-42fd-aa4c-ffe1adff275c";
        public static Guid guidTestCommandHereWeGoPackage = new Guid(guidTestCommandHereWeGoPackageString);

        public const string guidTestCommandHereWeGoPackageCmdSetString = "a984ead0-fa2a-4a28-b39d-265a810ad768";
        public static Guid guidTestCommandHereWeGoPackageCmdSet = new Guid(guidTestCommandHereWeGoPackageCmdSetString);

        public const string guidImagesString = "7912be6b-e64e-4ed2-8edb-ff629b56a953";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandHereWeGoId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}