// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddingSimpleCommand
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddingSimpleCommandPackageString = "c6c22c9f-6698-4f37-b588-c5685f612beb";
        public static Guid guidAddingSimpleCommandPackage = new Guid(guidAddingSimpleCommandPackageString);

        public const string guidAddingSimpleCommandPackageCmdSetString = "dbaae1e2-8d49-4c5d-bc0a-3a3f11a7edf1";
        public static Guid guidAddingSimpleCommandPackageCmdSet = new Guid(guidAddingSimpleCommandPackageCmdSetString);

        public const string guidImagesString = "e5d12f71-23b6-4d4c-a0f9-46e67303e8d7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SimpleCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}