// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GetSelection.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGetSelectionPackageString = "84b999df-77ad-4d55-be69-26d8033c9aea";
        public static Guid guidGetSelectionPackage = new Guid(guidGetSelectionPackageString);

        public const string guidGetSelectionPackageCmdSetString = "a6094191-90aa-4614-9cf4-7aac7c37a345";
        public static Guid guidGetSelectionPackageCmdSet = new Guid(guidGetSelectionPackageCmdSetString);

        public const string guidImagesString = "194e05b3-cf84-49cd-9237-6f939865ebe9";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int GetSelectionCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}