// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UseSVsActivityLogService.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidUseSVsActivityLogServicePackageString = "69e9e684-6607-4c5b-86c5-91a78365c35a";
        public static Guid guidUseSVsActivityLogServicePackage = new Guid(guidUseSVsActivityLogServicePackageString);

        public const string guidUseSVsActivityLogServicePackageCmdSetString = "3ca88bd9-272e-49d0-b2cf-ddeea24a0864";
        public static Guid guidUseSVsActivityLogServicePackageCmdSet = new Guid(guidUseSVsActivityLogServicePackageCmdSetString);

        public const string guidImagesString = "71493b77-3e6e-4dc9-9236-5a1834a69cac";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int SimpleCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}