// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutofacDIIntro.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAutofacDIIntroPackageString = "0791b5aa-209e-4b5c-ab3a-f09ec50d80ae";
        public static Guid guidAutofacDIIntroPackage = new Guid(guidAutofacDIIntroPackageString);

        public const string guidAutofacDIIntroPackageCmdSetString = "ea0932dd-e82a-40c6-bbe1-2dde1ec5028d";
        public static Guid guidAutofacDIIntroPackageCmdSet = new Guid(guidAutofacDIIntroPackageCmdSetString);

        public const string guidImagesString = "74d6e183-9ce4-451f-9ef1-d68a992f55ec";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TrialToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}