// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ActiveProcessWithToolWindow.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidActiveProcessWithToolWindowPackageString = "34651290-3afe-4a09-9b98-9972d7a173fa";
        public static Guid guidActiveProcessWithToolWindowPackage = new Guid(guidActiveProcessWithToolWindowPackageString);

        public const string guidActiveProcessWithToolWindowPackageCmdSetString = "ce40c358-cba6-40a2-8fcb-dbf215c77c74";
        public static Guid guidActiveProcessWithToolWindowPackageCmdSet = new Guid(guidActiveProcessWithToolWindowPackageCmdSetString);

        public const string guidImagesString = "afeff79b-c702-432f-bfe5-6547becb0dd2";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AsyncToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}