// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageEditor.e4a1796c-cbc7-4f0c-9114-0d396ff66a9d";
        public const string Name = "LinqLanguageEditor";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
