// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleToolWindow.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimpleToolWindowPackageString = "f0375f9b-76fa-4adb-957d-95a6f9472959";
        public static Guid guidSimpleToolWindowPackage = new Guid(guidSimpleToolWindowPackageString);

        public const string guidSimpleToolWindowPackageCmdSetString = "0d4521d5-2451-40d4-8a2e-53a9b8f4b50c";
        public static Guid guidSimpleToolWindowPackageCmdSet = new Guid(guidSimpleToolWindowPackageCmdSetString);

        public const string guidImagesString = "27222cf3-f7c2-489d-97c0-254e13e76592";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindowWithButtonCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}