// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleWebSearch.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimpleWebSearchPackageString = "39be0c55-7747-4a50-a5b6-d9476826b89d";
        public static Guid guidSimpleWebSearchPackage = new Guid(guidSimpleWebSearchPackageString);

        public const string guidSimpleWebSearchPackageCmdSetString = "da587d54-32dc-4e4f-b762-2cd5abe48811";
        public static Guid guidSimpleWebSearchPackageCmdSet = new Guid(guidSimpleWebSearchPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FindOnWebCommandId = 0x0100;
    }
}