// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixCommunityToolWindowGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixCommunityToolWindowGuid.68464fe7-5382-4948-b72c-cf988f5425a5";
        public const string Name = "VsixCommunityToolWindowGuid";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
