// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddMenuVsMainMenuBar.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddMenuVsMainMenuBarPackageString = "94afe47c-f606-4b95-8ac1-788e2710db97";
        public static Guid guidAddMenuVsMainMenuBarPackage = new Guid(guidAddMenuVsMainMenuBarPackageString);

        public const string guidAddMenuVsMainMenuBarPackageCmdSetString = "992b3cdc-61c1-4b76-8c60-6598e88530e1";
        public static Guid guidAddMenuVsMainMenuBarPackageCmdSet = new Guid(guidAddMenuVsMainMenuBarPackageCmdSetString);

        public const string guidImagesString = "c275e9e3-2560-4871-8b83-42cbb2d5b6cf";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MainMenuCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}