// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddMenuVsMainMenuBar.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddMenuVsMainMenuBarPackageString = "d8f67f70-b92c-4904-8a64-245ae8c2e10f";
        public static Guid guidAddMenuVsMainMenuBarPackage = new Guid(guidAddMenuVsMainMenuBarPackageString);

        public const string guidAddMenuVsMainMenuBarPackageCmdSetString = "33c3153d-5f40-4e71-a11e-50cf8575ecf6";
        public static Guid guidAddMenuVsMainMenuBarPackageCmdSet = new Guid(guidAddMenuVsMainMenuBarPackageCmdSetString);

        public const string guidImagesString = "5dbd87e1-c94b-4ae3-b5ea-07c651f71072";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int AddMenuVsMainMenuBarId = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}