// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WpfTextViewHostControl
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWpfTextViewHostControlPackageString = "5b7319de-d851-48ec-bdd3-b1ed68a49a8a";
        public static Guid guidWpfTextViewHostControlPackage = new Guid(guidWpfTextViewHostControlPackageString);

        public const string guidWpfTextViewHostControlPackageCmdSetString = "3c645f98-f4d9-4010-bf96-9fa97911af4c";
        public static Guid guidWpfTextViewHostControlPackageCmdSet = new Guid(guidWpfTextViewHostControlPackageCmdSetString);

        public const string guidImagesString = "4bb921b7-af05-44d6-887b-f5335a750f5a";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}