// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GetActiveProcess
{
    internal sealed partial class Vsix
    {
        public const string Id = "GetActiveProcess.8bacab68-5e7e-4a30-b31d-dfe312217b72";
        public const string Name = "GetActiveProcess";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
