// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TextBufferIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTextBufferIntroPackageString = "9db3e452-dee1-4960-bd96-b0133a636cab";
        public static Guid guidTextBufferIntroPackage = new Guid(guidTextBufferIntroPackageString);

        public const string guidTextBufferIntroPackageCmdSetString = "b22f20f0-5139-4bfa-a3b8-6e07f0dc03ed";
        public static Guid guidTextBufferIntroPackageCmdSet = new Guid(guidTextBufferIntroPackageCmdSetString);

        public const string guidImagesString = "3c586788-cdcb-4c3e-8fb6-986ed78ddcbb";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int BasicTextManipulationCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}