// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixCommandCommunity
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixCommandCommunity.6f6fb24f-ac1e-4d70-a085-34973632e0a0";
        public const string Name = "VsixCommandCommunity";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
