// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReadOptionsValues.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidReadOptionsValuesPackageString = "27988516-9079-46fd-a438-b4b8729e3fe4";
        public static Guid guidReadOptionsValuesPackage = new Guid(guidReadOptionsValuesPackageString);

        public const string guidReadOptionsValuesPackageCmdSetString = "8a93f5d5-d59b-4457-820b-3a509d0cb536";
        public static Guid guidReadOptionsValuesPackageCmdSet = new Guid(guidReadOptionsValuesPackageCmdSetString);

        public const string guidImagesString = "aab06980-f5aa-4ba8-bc82-ca8fbe642b2e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ReadIntOptionCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}