// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageServiceIntro
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageServiceIntro.2dd70268-4acf-4321-af16-bc1dc36d1d76";
        public const string Name = "LinqLanguageServiceIntro";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
