//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorWithToolBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorWithToolBox.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor With ToolBox - C# Sample.
        /// </summary>
        internal static string _100_ {
            get {
                return ResourceManager.GetString("100 ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample showing an editor that uses the tool box.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.0.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor With Toolbox - C# Sample.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TbxFile.tbx.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor with Toolbox.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor with Toolbox File.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Read Only].
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor With Toolbox files (*.tbx)\n*.tbx\n\n.
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _401_ {
            get {
                object obj = ResourceManager.GetObject("401 ", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
