// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleWebSearch.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimpleWebSearchPackageString = "39be0c55-7747-4a50-a5b6-d9476826b89d";
        public static Guid guidSimpleWebSearchPackage = new Guid(guidSimpleWebSearchPackageString);

        public const string guidSimpleWebSearchPackageCmdSetString = "da587d54-32dc-4e4f-b762-2cd5abe48811";
        public static Guid guidSimpleWebSearchPackageCmdSet = new Guid(guidSimpleWebSearchPackageCmdSetString);

        public const string guidImagesString = "3e8b16b0-1490-492b-aa69-3354046a3cf0";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FindOnWebCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}