// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutofacComnityToolKitNotWorking
{
    internal sealed partial class Vsix
    {
        public const string Id = "AutofacComnityToolKitNotWorking.84e52e34-47b9-49c6-82f0-39294e9a5442";
        public const string Name = "AutofacComnityToolKitNotWorking";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
