// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FilePathToContentTypeProviderIntro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFilePathToContentTypeProviderIntroPackageString = "74ed8a76-1c12-40fe-9d2b-d94a2757fb42";
        public static Guid guidFilePathToContentTypeProviderIntroPackage = new Guid(guidFilePathToContentTypeProviderIntroPackageString);

        public const string guidFilePathToContentTypeProviderIntroPackageCmdSetString = "89f53977-56e7-47e7-8099-864f66ca87cc";
        public static Guid guidFilePathToContentTypeProviderIntroPackageCmdSet = new Guid(guidFilePathToContentTypeProviderIntroPackageCmdSetString);

        public const string guidImagesString = "bf8a1ebb-72d6-40fb-959e-820fda51f0d8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}