// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebSearchMultipleOptions.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWebSearchMultipleOptionsPackageString = "96454401-ca43-4ef8-85eb-6d6b494c0a33";
        public static Guid guidWebSearchMultipleOptionsPackage = new Guid(guidWebSearchMultipleOptionsPackageString);

        public const string guidWebSearchMultipleOptionsPackageCmdSetString = "efb8b346-9d9f-446f-aac4-f8b3962f82e5";
        public static Guid guidWebSearchMultipleOptionsPackageCmdSet = new Guid(guidWebSearchMultipleOptionsPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int WebSearchCommandId = 0x0100;
    }
}