// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EditorWithToolBox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidEditorPackageString = "6d688609-4f87-4b6c-9ea5-7ca739dae8de";
        public static Guid guidEditorPackage = new Guid(guidEditorPackageString);

        public const string guidEditorPackageCmdSetString = "65c01841-8c9c-4ac9-bf03-15c6edee9653";
        public static Guid guidEditorPackageCmdSet = new Guid(guidEditorPackageCmdSetString);

        public const string guidImagesString = "645d32a6-7aa9-439a-9020-f8973ad7bc63";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}