// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommunityToolKitGetProcess
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommunityToolKitGetProcess.09f181ed-65cb-4c2f-8912-39407bbf4f09";
        public const string Name = "CommunityToolKitGetProcess";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
