// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutofacComnityToolKitGetProc
{
    internal sealed partial class Vsix
    {
        public const string Id = "AutofacComnityToolKitGetProc.bbf7e40d-c1b0-429f-afb9-ce19034b85c0";
        public const string Name = "AutofacComnityToolKitGetProc";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
