// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace AutofacComnityToolKitGetProc
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AutofacComnityToolKitGetProcString = "3ffeb9ef-84b9-419a-93df-33e03d0cc6da";
        public static Guid AutofacComnityToolKitGetProc = new Guid(AutofacComnityToolKitGetProcString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}