//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 17.0.0.4
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace ManifestToCode
{
    public static class MyImageIds
    {
        public const string AssetsGuidString = "{d6b7646f-8cef-49d0-97f1-14940add7126}";
        public static readonly Guid AssetsGuid = new Guid(AssetsGuidString);

        public const int Save = 0;
    }
}
