//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 17.0.0.4
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace ManifestToCode
{
    public static class MyImageIds
    {
        public const string AssetsGuidString = "{f7d7b6c8-5cf5-410f-9564-ea0d9befbbc8}";
        public static readonly Guid AssetsGuid = new Guid(AssetsGuidString);

        public const int Save = 0;
    }
}
