//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 17.0.0.4
// </auto-generated>
//-----------------------------------------------------------------------------

using Microsoft.VisualStudio.Imaging.Interop;

namespace ManifestToCode
{
    public static class MyMonikers
    {
        public static ImageMoniker Save { get { return new ImageMoniker { Guid = MyImageIds.AssetsGuid, Id = MyImageIds.Save }; } }
    }
}
