// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassificationTypeRegistrySvcOldStyle.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidClassificationTypeRegistrySvcOldStylePackageString = "32fa5481-ea8c-4eca-a696-fb97e113a1e7";
        public static Guid guidClassificationTypeRegistrySvcOldStylePackage = new Guid(guidClassificationTypeRegistrySvcOldStylePackageString);

        public const string guidClassificationTypeRegistrySvcOldStylePackageCmdSetString = "c4734cb3-62a2-4bc7-9795-99d488a90142";
        public static Guid guidClassificationTypeRegistrySvcOldStylePackageCmdSet = new Guid(guidClassificationTypeRegistrySvcOldStylePackageCmdSetString);

        public const string guidImagesString = "14fa60fc-ddea-4637-8072-90d2dfc5506b";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}