// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace IFileExtRegSerNotWorking.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidIFileExtRegSerNotWorkingPackageString = "82ce21c1-18f4-408a-95e9-d0cf5b71cdba";
        public static Guid guidIFileExtRegSerNotWorkingPackage = new Guid(guidIFileExtRegSerNotWorkingPackageString);

        public const string guidIFileExtRegSerNotWorkingPackageCmdSetString = "3ee3701b-1837-4fcd-bf9c-228c7a9f641c";
        public static Guid guidIFileExtRegSerNotWorkingPackageCmdSet = new Guid(guidIFileExtRegSerNotWorkingPackageCmdSetString);

        public const string guidImagesString = "d3fc3c4c-1b6a-491c-ab30-7ba3bea268d5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}