// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace QuickInfoCustomContentType
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidQuickInfoCustomContentTypePackageString = "4e5426da-371c-4e4b-9cb9-90dce73174c1";
        public static Guid guidQuickInfoCustomContentTypePackage = new Guid(guidQuickInfoCustomContentTypePackageString);

        public const string guidQuickInfoCustomContentTypePackageCmdSetString = "5c1108b8-1e2e-4578-8618-82c0cf741ea4";
        public static Guid guidQuickInfoCustomContentTypePackageCmdSet = new Guid(guidQuickInfoCustomContentTypePackageCmdSetString);

        public const string guidImagesString = "695da89a-febd-4869-b21e-0734f944a572";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}