// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsTextManagerIntro.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsTextManagerIntroPackageString = "ec846a6d-9e5c-4d6d-ac01-08ebd19a230d";
        public static Guid guidVsTextManagerIntroPackage = new Guid(guidVsTextManagerIntroPackageString);

        public const string guidVsTextManagerIntroPackageCmdSetString = "0186637c-c9de-4545-af89-a9dcd12a3c97";
        public static Guid guidVsTextManagerIntroPackageCmdSet = new Guid(guidVsTextManagerIntroPackageCmdSetString);

        public const string guidImagesString = "0f82d824-847c-47f7-b30e-939e323c2d5a";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int TestCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}