// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProvideAutoLoad.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProvideAutoLoadPackageString = "449d28b3-1d8e-4860-a448-87cc08098f3c";
        public static Guid guidProvideAutoLoadPackage = new Guid(guidProvideAutoLoadPackageString);

        public const string guidProvideAutoLoadPackageCmdSetString = "03fa143e-7834-4179-9fd5-edba6772c20f";
        public static Guid guidProvideAutoLoadPackageCmdSet = new Guid(guidProvideAutoLoadPackageCmdSetString);

        public const string guidImagesString = "b11efc6f-52b6-4686-9f4e-b9226d65b240";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ATrialCommandId = 0x0100;
        public const int TopLevelMenu = 0x1021;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}