// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VsixBlankCommunity
{
    internal sealed partial class Vsix
    {
        public const string Id = "VsixBlankCommunity.6dd93da5-8e27-4ca0-9e22-cf5aec0d617c";
        public const string Name = "VsixBlankCommunity";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Baker Hughes";
        public const string Tags = "";
    }
}
