// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditorPrepare
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LinqLanguageEditorPrepareString = "10b5b755-97b2-4c4f-a41d-484f4855c9d1";
        public static Guid LinqLanguageEditorPrepare = new Guid(LinqLanguageEditorPrepareString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LinqToolWindowCommandId = 0x0100;
    }
}