// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddingMonikerIcon.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddingMonikerIconPackageString = "61222390-1538-4033-8989-3058e4b59fbc";
        public static Guid guidAddingMonikerIconPackage = new Guid(guidAddingMonikerIconPackageString);

        public const string guidAddingMonikerIconPackageCmdSetString = "15b7b81d-ab9a-4217-8fed-adc110089572";
        public static Guid guidAddingMonikerIconPackageCmdSet = new Guid(guidAddingMonikerIconPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MainMenuCommandId = 0x0100;
    }
}